id = "min-theme"
name = "Min Theme for Zed"
version = "0.1.0"
schema_version = 1
authors = ["castrogarciajs <castrogarcia.mjs@gmail.com>"]
description = "A minimal theme for Zed that comes in dark and light."
repository = "https://github.com/castrogarciajs/zed-min-theme"
